sudo: false
language: ruby
cache:
  - bundler
rvm:
  - 2.1
  - 2.2
script:
  - bundle exec rake spec
  - mkdir /home/travis/bin
  - echo 'echo $@' > /home/travis/bin/bcn
  - chmod +x /home/travis/bin/bcn
  - bundle exec bin/bcnd
